/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 room.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/room-transformed.glb')
  return (
    <group {...props} dispose={null} >
       <PerspectiveCamera name="camera" makeDefault position={[2,6, 5]} /> 
      <mesh geometry={nodes.Text.geometry} material={materials['default']} position={[-0.99, 2.03, -1.2]} rotation={[Math.PI / 2, 0, 0]} scale={0.23} />
      <mesh geometry={nodes['Floor_-_1'].geometry} material={materials['2']} position={[0.12, 0.05, 0.12]} />
      <mesh geometry={nodes.Wall.geometry} material={materials['1']} />
      <mesh geometry={nodes['Floor_-_2'].geometry} material={materials['3']} position={[0.11, 0.11, 0.11]} scale={0.87} />
      <mesh geometry={nodes['Chair_-_1'].geometry} material={materials['6']} position={[-0.04, 0.17, -0.34]} rotation={[Math.PI / 2, 1.43, -1.43]} scale={[0.44, 0.36, 0.44]} />
      <group position={[0.02, 0.21, -0.72]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Cube008_1.geometry} material={materials['8']} />
        <mesh geometry={nodes.Cube008_2.geometry} material={materials['5']} />
      </group>
      <group position={[-0.59, 0.72, 1.06]} rotation={[-2.34, 1.2, 0.8]} scale={0.59}>
        <mesh geometry={nodes.Cylinder018.geometry} material={materials['3']} />
        <mesh geometry={nodes.Cylinder018_1.geometry} material={materials['6']} />
      </group>
      <mesh geometry={nodes['Chair_-_2'].geometry} material={materials['5']} position={[-0.15, 0.15, 0.72]} rotation={[0.07, 0, 0]} scale={[0.19, 0.13, 0.19]} />
      <mesh geometry={nodes.Framework.geometry} material={materials['7']} position={[-1.24, 1.68, -0.35]} rotation={[0, 0, -Math.PI / 2]} scale={0.49} />
      <group position={[-1.2, 1.91, -0.57]} rotation={[0.22, 0, 0]}>
        <mesh geometry={nodes.Plane010.geometry} material={materials['3']} />
        <mesh geometry={nodes.Plane010_1.geometry} material={materials['6']} />
        <mesh geometry={nodes.Plane010_2.geometry} material={materials['4']} />
      </group>
      <mesh geometry={nodes.Pin.geometry} material={materials['6']} position={[-1.09, 1.71, -0.21]} rotation={[-0.33, 0, -Math.PI / 2]} scale={0.06} />
      <mesh geometry={nodes.Paper.geometry} material={materials['4']} position={[-1.23, 1.57, -0.02]} rotation={[-0.33, 0, 0]} />
      <group position={[-0.83, 1.23, -0.16]}>
        <mesh geometry={nodes.Plane014.geometry} material={materials['6']} />
        <mesh geometry={nodes.Plane014_1.geometry} material={materials['7']} />
      </group>
      <mesh geometry={nodes['Stand_Monitor_-_1'].geometry} material={materials['6']} position={[0, 0.03, 0.15]} />
      <group position={[-0.67, 1.37, -0.93]} rotation={[Math.PI / 2, 0, Math.PI / 6]}>
        <mesh geometry={nodes.Plane035.geometry} material={materials['6']} />
        <mesh geometry={nodes.Plane035_1.geometry} material={materials['7']} />
      </group>
      <mesh geometry={nodes['Stand_Monitor_-_2'].geometry} material={materials['6']} position={[-0.72, 0.82, -0.95]} rotation={[0, -Math.PI / 6, 0]} />
      <group position={[0.83, 1.53, -1.25]} scale={1.03}>
        <mesh geometry={nodes.Cube004.geometry} material={materials['5']} />
        <mesh geometry={nodes.Cube004_1.geometry} material={materials['7']} />
      </group>
      <group position={[0.83, 2.02, -1.13]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.52, 0.03, 0.01]}>
        <mesh geometry={nodes.Cube009.geometry} material={materials['3']} />
        <mesh geometry={nodes.Cube009_1.geometry} material={materials['5']} />
      </group>
      <group position={[-0.42, 0.53, 1.15]} rotation={[-Math.PI / 2, 0, 0.28]} scale={[0.02, 0.03, 0.02]}>
        <mesh geometry={nodes.Cylinder004.geometry} material={materials['8']} />
        <mesh geometry={nodes.Cylinder004_1.geometry} material={materials['6']} />
        <mesh geometry={nodes.Cylinder004_2.geometry} material={materials['5']} />
      </group>
      <mesh geometry={nodes.Mug.geometry} material={materials['1']} position={[-0.42, 0.9, 0.36]} rotation={[Math.PI / 2, 0, 0.99]} scale={0.05} />
      <mesh geometry={nodes['Book_-_2'].geometry} material={materials['6']} position={[-0.24, 0.77, -0.96]} rotation={[0, 0.83, 0]} scale={0.12} />
      <mesh geometry={nodes['Book_-_1'].geometry} material={materials['4']} position={[-0.08, 0.82, -0.98]} scale={0.11} />
      <group position={[-0.64, 0.89, 0.96]} rotation={[0.01, 0.27, 0.25]} scale={[0.75, 0.53, 0.62]}>
        <mesh geometry={nodes.Plane045.geometry} material={materials['8']} />
        <mesh geometry={nodes.Plane045_1.geometry} material={materials['2']} />
        <mesh geometry={nodes.Plane045_2.geometry} material={materials['4']} />
      </group>
      <mesh geometry={nodes['Photo_-_2'].geometry} material={materials['4']} position={[-1.25, 1.54, 1.04]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.16} />
      <mesh geometry={nodes['Photo_-_3'].geometry} material={materials['3']} position={[-1.25, 1.2, 0.71]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.16} />
      <group position={[-1.25, 2.07, 0.85]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.26}>
        <mesh geometry={nodes.Circle011.geometry} material={materials['6']} />
        <mesh geometry={nodes.Circle011_1.geometry} material={materials['1']} />
        <mesh geometry={nodes.Circle011_2.geometry} material={materials['4']} />
      </group>
      <mesh geometry={nodes.Mouse.geometry} material={materials['6']} position={[-0.58, 0.85, -0.54]} rotation={[-Math.PI, 1.12, -Math.PI]} scale={0.03} />
      <mesh geometry={nodes.Smoke.geometry} material={materials['7']} position={[-0.45, 1.03, 0.28]} scale={0.03} />
      <group position={[-0.52, 0.83, -0.14]} rotation={[0, Math.PI / 2, 0]} scale={0.03}>
        <mesh geometry={nodes.Plane001.geometry} material={materials['6']} />
        <mesh geometry={nodes.Plane001_1.geometry} material={materials['4']} />
      </group>
    </group>
  )
}

<Model position={[4, 5, 6]} />
useGLTF.preload('/room-transformed.glb')
